# Handling imbalanced Dataset with Machine Learning

In [1]:
# Weblink for Credit Card Fraud Detection Data set:
# https://www.kaggle.com/mlg-ulb/creditcardfraud

import pandas as pd
df = pd.read_csv('creditcard.csv')
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [2]:
df.shape

(284807, 31)

In [3]:
# counting number of Null values in each feature / column
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [4]:
# Fraud Detection is a Classification problems. So lets focus on "Class" feature
df['Class']

0         0
1         0
2         0
3         0
4         0
         ..
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64

In [5]:
# counting the frequency of each type of value in the "Class" feature
# 0 = not fraud
# 1 = fraud
df['Class'].value_counts()

# As, the percentage of 1's is very less = 492/(492+284315) = 0.17 %
# so, the data is imbalanced

0    284315
1       492
Name: Class, dtype: int64

In [6]:
# Splitting the given dataset into 2 datasets
# Independent Features (X) = All features Except "Class"
# Dependent Features (Y) = "Class"
X = df.drop("Class",axis=1)
y = df.Class

#### Cross Validation like KFold and Hyperparameter Tuning

In [7]:
# 1st Technique ~ LogisticRegression

In [8]:
# Lets import all the necessary Librarires for "Logistic Regression Model"
from sklearn.linear_model import LogisticRegression

# Just "accuracy" is not enough. Other "metrices" should also be checked
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

# For Cross Validation
from sklearn.model_selection import KFold
# For KFold
import numpy as np

# to perform GridSearchCV
from sklearn.model_selection import GridSearchCV

In [9]:
 #Cross Validation through Hyper-Parameter tuning
10.0**np.arange(-2,3)
# o/p = 10^-2 , 10^-1 , 10^0 , 10^1 , 10^2 

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [10]:
# Implementing "Logistic Regression Model"
log_class=LogisticRegression() #Intializing Logarithmic classifier
grid={'C':10.0**np.arange(-2,3),'penalty':['l1','l2']} #grid search parameters for Hyper-Parameter tuning
cv = KFold(n_splits=5, random_state=None,shuffle=False) # cv = Cross Validation parameters

In [11]:
# train -test split
from sklearn.model_selection import train_test_split

# reserving 70% dataset for training and remaining 30% for Testing purpose
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7) 

In [12]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro') #'f1_macro' is a scoring parameter
clf.fit(X_train,y_train) # implementing FIT on Training dataset
#  Fit Training  will take more time to execute ^|^

C:\Users\Kapil Wanaskar\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Kapil Wanaskar\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Kapil Wanaskar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\Kapil Wanaskar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 447, in _che

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [13]:
#o/p code
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred)) 
print(classification_report(y_test,y_pred))

# 0.9989 ~ 99.9 % accuracy # do not beleive the higher accuracy score of Imbalanced Dataset

[[85282    32]
 [   40    89]]
0.9991573329588147
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85314
           1       0.74      0.69      0.71       129

    accuracy                           1.00     85443
   macro avg       0.87      0.84      0.86     85443
weighted avg       1.00      1.00      1.00     85443



In [14]:
# 2nd Technique ~ RandomForestClassifier

In [15]:
X_train.shape

(199364, 30)

In [16]:
y_train.shape

(199364,)

In [17]:
y_train.value_counts()

0    199001
1       363
Name: Class, dtype: int64

In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train,y_train)
#  Fit Training  will take more time to execute ^|^

RandomForestClassifier()

In [19]:
# copy pasted above o/p code
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred)) 
print(classification_report(y_test,y_pred))

# (precision, recall, f1-score) improved from
# ( 0.69, 0.63, 0.66) in Logistic Regression to (0.87, 0.75, 0.80 ) in RandomForestClassifier

# (False +ve, False -ve) improved from
# ( 38, 54) in Logistic Regressi on to (15, 34 ) in RandomForestClassifier

[[85304    10]
 [   30    99]]
0.9995318516437859
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85314
           1       0.91      0.77      0.83       129

    accuracy                           1.00     85443
   macro avg       0.95      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [20]:
# to make the dataset more BALANCED
# chainging the "weight"age of each class 0 & 1
class_weight = dict({0:1,1:100})
# old classes 0's are changed to new 1's
# old classes 1's are changed to new 100's (given 100x more importance to old classes 1's )

In [21]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train,y_train)
# Fit Training will take more time to execute ^|^

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [22]:
# copy pasted above o/p code
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred)) 
print(classification_report(y_test,y_pred))

# (precision, recall, f1-score) HARDLY improved from
# (0.87, 0.75, 0.80 ) in RandomForestClassifier to (0.92, 0.75, 0.82) with extra ClassWeights in RandomForestClassifier

# (False +ve, False -ve) BARELY improved from
# (15,34) in RandomForestClassifier TO (9,34) with extra ClassWeights  in RandomForestClassifier 

[[85302    12]
 [   27   102]]
0.9995435553526912
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85314
           1       0.89      0.79      0.84       129

    accuracy                           1.00     85443
   macro avg       0.95      0.90      0.92     85443
weighted avg       1.00      1.00      1.00     85443

